apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ingress.issuer }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: https://api.buypass.com/acme/directory
    email: {{ .Values.ingress.email }}
    privateKeySecretRef:
      name: {{ .Values.ingress.issuer }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.className }}
