{{- if eq .Values.ingress.issuer "buypass-prod" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: buypass-prod
spec:
  acme:
    email: {{ .Values.ingress.email }}
    server: https://api.buypass.com/acme/directory
    privateKeySecretRef:
      name: buypass-prod
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}