apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  FLEET_MYSQL_DATABASE: {{ .Values.database.name | quote }}
  FLEET_MYSQL_ADDRESS: {{ .Values.database.address | quote }}
  FLEET_REDIS_ADDRESS: {{ .Values.redis.address | quote }}
  FLEET_SERVER_ADDRESS: {{ .Values.env.FLEET_SERVER_ADDRESS | quote }}
  FLEET_SERVER_TLS: {{ .Values.env.FLEET_SERVER_TLS | quote }}
  FLEET_OSQUERY_TLS_DISABLE: {{ .Values.env.FLEET_OSQUERY_TLS_DISABLE | quote }}
  FLEET_MDM_ENABLE: {{ .Values.env.FLEET_MDM_ENABLE | quote }}
  FLEET_DISABLE_UPDATES: {{ .Values.env.FLEET_DISABLE_UPDATES | quote }}
