apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fleet.mysql.secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.secrets.mysql.user }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysql.password }}
