name: Deploy FleetDM to GKE via Helm

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  CLUSTER_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
  SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

jobs:
  deploy:
    name: Deploy FleetDM Helm Chart
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_ZONE }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3
      
      - name: Helm Lint Check
        run: |
          helm lint ./k8s/fleet-helm \
            --values ./k8s/fleet-helm/values/dev.yaml

      # - name: Deploy FleetDM via Helm
      #   run: |
      #     export USE_GKE_GCLOUD_AUTH_PLUGIN=False
      #     helm upgrade --install fleet ./k8s/fleet-helm \
      #       --namespace fleet \
      #       --create-namespace \
      #       -f ./k8s/fleet-helm/values/dev.yaml

      - name: Get short SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Retag and push fleet image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/fleetdm
          IMAGE_TAG=main-${{ steps.vars.outputs.sha }}

          docker pull fleetdm/fleet:HEAD
          docker tag fleetdm/fleet:HEAD $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Delete existing DB init job if exists
        run: |
          kubectl delete job fleet-db-init -n fleet --ignore-not-found

      - name: Deploy FleetDM via Helm
        run: |
          export USE_GKE_GCLOUD_AUTH_PLUGIN=False
          helm upgrade --install fleet ./k8s/fleet-helm \
            --namespace fleet \
            --create-namespace \
            -f ./k8s/fleet-helm/values/dev.yaml \
            --set image.repository=ghcr.io/${{ github.repository_owner }}/fleetdm \
            --set image.tag=main-${{ steps.vars.outputs.sha }}

      - name: Run Integration Test
        env:
          FLEET_EMAIL: ${{ secrets.FLEET_EMAIL }}
          FLEET_PASSWORD: ${{ secrets.FLEET_PASSWORD }}
        run: |
          chmod +x ./scripts/integrationTest.sh
          ./scripts/integrationTest.sh
      
      - name: Smoke test - check /login
        run: |
          sleep 10
          curl -s -o /dev/null -w "%{http_code}" http://fleet.34.77.188.249.nip.io/login | grep 200
