name: Deploy to GKE

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig from secret
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.K8S }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Helm upgrade/install
        run: |
          helm upgrade --install fleet ./k8s/fleet-helm \
            --namespace fleet --create-namespace \
            -f ./k8s/fleet-helm/values/dev.yaml
