name: Deploy FleetDM to GKE via Helm

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  CLUSTER_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
  SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

jobs:
  deploy:
    name: Deploy FleetDM Helm Chart
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_ZONE }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3
      
      - name: Helm Lint Check
        run: |
          helm lint ./k8s/fleet-helm \
            --values ./k8s/fleet-helm/values/dev.yaml

      - name: Deploy FleetDM via Helm
        run: |
          export USE_GKE_GCLOUD_AUTH_PLUGIN=False
          helm upgrade --install fleet ./k8s/fleet-helm \
            --namespace fleet \
            --create-namespace \
            -f ./k8s/fleet-helm/values/dev.yaml
      
      - name: Smoke test - check /login
        run: |
          sleep 10 # Подождать, чтобы Ingress и сервисы успели подняться
          curl -s -o /dev/null -w "%{http_code}" http://fleet.34.77.188.249.nip.io/login | grep 200
