name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'  # для Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER_NAME" \
            --zone "$GKE_CLUSTER_ZONE" \
            --project "$GCP_PROJECT_ID"
        env:
          GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          GKE_CLUSTER_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Deploy with Helm
        run: |
          helm upgrade --install fleet ./k8s/fleet-helm \
            --namespace fleet \
            --create-namespace \
            -f ./k8s/fleet-helm/values/dev.yaml