name: CI with kind

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Kubernetes with kind
        uses: helm/kind-action@v1.8.0
        with:
          config: |
            kind: Cluster
            apiVersion: kind.x-k8s.io/v1alpha4
            nodes:
              - role: control-plane

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Deploy Helm chart
        run: |
          helm upgrade --install fleet ./k8s/fleet-helm \
            --namespace fleet --create-namespace \
            -f ./k8s/fleet-helm/values/dev.yaml

      - name: Check app deployment
        run: |
          kubectl rollout status deployment/fleet -n fleet
          kubectl get all -n fleet